server:
    port: 8084

spring:
    application:
        name: service-zuul

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
zuul:
    routes:
        a:
            path: /a/**
            serviceId: service-ribbon
        b:
            path: /b/**
            serviceId: service-feign
